language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "lawhvictoria-github"
    token:
      secure: "b040e7d261220971737560c20065279a069a9fbb"
jdk:
  - oraclejdk8
before_script:
  - cd 309-SystemsRun/
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
